var colorsArray = {
    colors:[{
            "name":"green",
            "red":"#F00",
            "green":"#0F0",
            "blue":"#00F"
        },
        {
            "name":"yellow",
            "red":"#F00",
            "green":"#0F0",
            "blue":"#00F"
        },
        {
            "name":"red",
            "red":"#F00",
            "green":"#0F0",
            "blue":"#00F"
        },
        {
            "name":"blue",
            "red":"#F00",
            "green":"#0F0",
            "blue":"#00F"
        },
        {
            "name":"orange",
            "red":"#F00",
            "green":"#0F0",
            "blue":"#00F"
        }
    ]
  }
