var colorsArray = {
    "colors":[{
            "name":"green",
            "red":"#f00",
            "green":"#0f0",
            "blue":"#00f"
        },
        {
            "name":"yellow",
            "red":"#f00",
            "green":"#0f0",
            "blue":"#00f"
        },
        {
            "name":"red",
            "red":"#f00",
            "green":"#0f0",
            "blue":"#00f"
        },
        {
            "name":"blue",
            "red":"#f00",
            "green":"#0f0",
            "blue":"#00f"
        },
        {
            "name":"orange",
            "red":"#f00",
            "green":"#0f0",
            "blue":"#00f"
        }
    ]
  };
